
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.173.133:3306/12306Impl?useUnicode=true&characterEncoding=utf-8&useSSL=false&AllowPublicKeyRetrieval=true
    username: root
    password: 12345678
    druid:
      max-active: 80
      initial-size: 10
      min-evictable-idle-time-millis: 300000
      max-wait: 30000
  data:
    redis:
      host: 192.168.173.133
      port: 6379
      password: 123456
  application:
    name: 12306-user-service

service:
  cache:
    prefix: 12306-user-service
    bloom-filter:
      name: user_register_cache_penetration_bloom_filter
      expected-insertions: 64
      false-probability: 0.003

server:
  port: 9001
