spring:
  datasource:
    url: jdbc:mysql://localhost:3306/12306Impl?useUnicode=true&characterEncoding=utf-8&useSSL=false&AllowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 130
      initial-size: 10
      min-evictable-idle-time-millis: 300000
      max-wait: 30000
